### ISSUE TITLE
'Can't locate object method "set_from"' errors cause conversion to fail

### ISSUE THREAD

**Issue by chrispitude** [mirod/mif2mml#1]
In this testcase, three MIF equations cause conversion to fail with the following errors:

```
./mif2mml.pl "pp_b65.mif" 2>&1 | tee "pp_b65_mml.out"
Can't locate object method "set_from" via package "<mo>*</mo>pelt=HASH(0x7fffcd52ebd8)" (perhaps you forgot to load "<mo>*</mo>pelt=HASH(0x7fffcd52ebd8)"?) at (eval 38) line 2737.
./mif2mml.pl "pp_b60.mif" 2>&1 | tee "pp_b60_mml.out"
Can't locate object method "set_from" via package "<mo>*</mo>pelt=HASH(0x7fffe30ca370)" (perhaps you forgot to load "<mo>*</mo>pelt=HASH(0x7fffe30ca370)"?) at (eval 38) line 2737.
./mif2mml.pl "pp_b66.mif" 2>&1 | tee "pp_b66_mml.out"
Can't locate object method "set_from" via package "<mo>*</mo>pelt=HASH(0x7fffde0c5528)" (perhaps you forgot to load "<mo>*</mo>pelt=HASH(0x7fffde0c5528)"?) at (eval 38) line 2737.
```

(Note that I am using a modified version of mif2mml which applies a particular meaning to "newfunction"; this hack must be propagated to your working copy to debug.)

[mif_issue.zip](https://github.com/mirod/mif2mml/files/3290731/mif_issue.zip)

To reproduce, unpack the archive, move to the directory, and type `make`.

**Comment by chrispy-snps** [comment]
I fixed this by changing

```
    #newfunction => sub { return '<mo>*</mo>' . shift; },
```

to

```
    newfunction => sub { pre_op('*', shift); },
```

The "bug" was simply because the old newfunction hack code was not upgraded from string-based parsing to element-based parsing. Because the newfunction hack is not present in the production release of mif2mml, this issue can be closed.
